#pragma once

#define ROUND_DIV_UP(DIVIDEND, DIVISOR) (((DIVIDEND) + (DIVISOR) - 1) / (DIVISOR))
#define ROUND_UP(VALUE, PRECISION) (ROUND_DIV_UP((VALUE), (PRECISION)) * (PRECISION))
#define ROUND_DOWN(VALUE, PRECISION) (((VALUE) / (PRECISION)) * (PRECISION))